services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: "1"
      AWS_DEFAULT_REGION: ap-south-1
      LOCALSTACK_AUTH_TOKEN: ls-lAyaBuZE-GIBE-7884-8487-SUYuYEwe9fdd
    volumes:
      - localstack_data:/var/lib/localstack
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  localstack_data:
  redis_data: